name: 'Setup .NET'
description: 'Setup .NET SDK and restore dependencies'

inputs:
  dotnet-version:
    description: '.NET SDK version to use'
    required: true
    default: '9.0.x'

runs:
  using: 'composite'
  steps:
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ inputs.dotnet-version }}

    - name: Restore dependencies
      shell: bash
      run: dotnet restore
